//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<int> deptId { get; set; }
        public Nullable<int> locationId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Location Location { get; set; }
    }
}
