//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeWebServicesDemo.ThomasBayerRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://thomas-bayer.com/blz/", ConfigurationName="ThomasBayerRef.BLZServicePortType")]
    public interface BLZServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="http://thomas-bayer.com/blz/BLZService/getBankResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="details")]
        ConsumeWebServicesDemo.ThomasBayerRef.detailsType getBank(string blz);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="http://thomas-bayer.com/blz/BLZService/getBankResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="details")]
        System.Threading.Tasks.Task<ConsumeWebServicesDemo.ThomasBayerRef.detailsType> getBankAsync(string blz);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thomas-bayer.com/blz/")]
    public partial class detailsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bezeichnungField;
        
        private string bicField;
        
        private string ortField;
        
        private string plzField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string bezeichnung {
            get {
                return this.bezeichnungField;
            }
            set {
                this.bezeichnungField = value;
                this.RaisePropertyChanged("bezeichnung");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string bic {
            get {
                return this.bicField;
            }
            set {
                this.bicField = value;
                this.RaisePropertyChanged("bic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ort {
            get {
                return this.ortField;
            }
            set {
                this.ortField = value;
                this.RaisePropertyChanged("ort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string plz {
            get {
                return this.plzField;
            }
            set {
                this.plzField = value;
                this.RaisePropertyChanged("plz");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BLZServicePortTypeChannel : ConsumeWebServicesDemo.ThomasBayerRef.BLZServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BLZServicePortTypeClient : System.ServiceModel.ClientBase<ConsumeWebServicesDemo.ThomasBayerRef.BLZServicePortType>, ConsumeWebServicesDemo.ThomasBayerRef.BLZServicePortType {
        
        public BLZServicePortTypeClient() {
        }
        
        public BLZServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BLZServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLZServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLZServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsumeWebServicesDemo.ThomasBayerRef.detailsType getBank(string blz) {
            return base.Channel.getBank(blz);
        }
        
        public System.Threading.Tasks.Task<ConsumeWebServicesDemo.ThomasBayerRef.detailsType> getBankAsync(string blz) {
            return base.Channel.getBankAsync(blz);
        }
    }
}
